language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.3

before-install:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction --dev

script:
  - php -S 127.0.0.1:8000 -t tests/CurlRox/ &> /dev/null &
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: proclnas@gmail.com